src/viralhostrange/live_settings/urls.py
from django.urls import re_path

from live_settings import views

app_name = "live_settings"
urlpatterns = [
    re_path(r"^update/(?P<slug>[a-zA-Z][\w]*)/$", views.change_value, name="update")
]

src/viralhostrange/viralhostrange/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include, re_path
from django.views.static import serve

from viralhostrange import settings
from viralhostrangedb import views
from viralhostrangedb.sitemap import my_sitemaps

urlpatterns = [
    path('', include('django_kubernetes_probes.urls')),
    path('', include('basetheme_bootstrap.urls')),
    path('', include('viralhostrangedb.urls')),
    path('api/', include('viralhostrangedb.urls_api')),
    # path('api/', include('webapi.urls')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('settings/', include("live_settings.urls")),
    path('', views.index, name='home'),
    path('sitemap.xml', sitemap, {'sitemaps': my_sitemaps},
         name='django.contrib.sitemaps.views.sitemap')
]

if not settings.DEBUG:
    urlpatterns.append(
        re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT})
    )
urlpatterns.append(
    re_path(r'^media/(?P<path>.*)$', views.xsendfile_serve)
)

src/viralhostrange/viralhostrangedb/urls.py
from django.urls import path, re_path
from django.views.i18n import JavaScriptCatalog

from viralhostrangedb import views

data_source_wizard = views.DataSourceWizard.as_view(url_name='viralhostrangedb:data-source-create-step')

app_name = 'viralhostrangedb'
urlpatterns = [
    path('', views.index, name='home'),
    path('import/data-source/', views.file_import, name='file-import-view'),
    # re_path(r'^data_source/(?P<pk>\d+)/edit/$', views.file_import, name='data-source-edit'),
    re_path(
        r'^data-source/pending-mapping/$',
        views.DataSourceMappingPendingListView.as_view(),
        name='data-source-pending-mapping-list',
    ),
    path('explore/', views.browse, name='browse'),
    re_path(r'^explore/css/(?P<slug>[^/]*)$', views.custom_css, name='custom_css'),
    path('download/', views.download_responses, name='download_responses'),
    path('data-source/', views.DataSourceListView.as_view(), name='data-source-list'),
    re_path(r'^data-source/(?P<pk>\d+)/download/$', views.data_source_download, name='data-source-download'),
    re_path(r'^data-source/(?P<pk>\d+)/update/$', views.data_source_data_update, name='data-source-data-update'),
    re_path(r'^data-source/(?P<pk>\d+)/edit/$', views.DataSourceUpdateView.as_view(), name='data-source-update'),
    re_path(r'^data-source/(?P<pk>\d+)/virus/update/$', views.data_source_virus_update, name='data-source-virus-update'),
    re_path(r'^data-source/(?P<pk>\d+)/host/update/$', views.data_source_host_update, name='data-source-host-update'),
    re_path(r'^data-source/(?P<pk>\d+)/virus/delete/$', views.data_source_virus_delete, name='data-source-virus-delete'),
    re_path(r'^data-source/(?P<pk>\d+)/host/delete/$', views.data_source_host_delete, name='data-source-host-delete'),
    re_path(r'^data-source/(?P<pk>\d+)/delete/$', views.DataSourceDeleteView.as_view(), name='data-source-delete'),
    re_path(r'^data-source/(?P<pk>\d+)/$', views.DataSourceDetailView.as_view(), name='data-source-detail'),
    re_path(r'^data-source/(?P<pk>\d+)/explore/$', views.SelectDataFromDataSourceView.as_view(), name='data-source-browse'),
    re_path(r'^data-source/(?P<pk>\d+)/explore_by_virus_and_host/$', views.SelectVirusAndHostFromDataSourceView.as_view(),
        name='data-source-browse-by-virus-and-host'),
    re_path(r'^data-source/(?P<pk>\d+)/mapping/edit-as-label/$', views.data_source_mapping_edit,
        name='data-source-mapping-label-edit'),
    re_path(r'^data-source/(?P<pk>\d+)/mapping/edit/$', views.data_source_mapping_range_edit,
        name='data-source-mapping-edit'),
    re_path(r'^data-source-contribution/(?P<step>.+)/$', data_source_wizard, name='data-source-create-step'),
    path('data-source-contribution/', data_source_wizard, name='data-source-create'),
    re_path(r'^data-source/(?P<pk>\d+)/contact/$', views.contact_data_source_owner, name='data-source-contact'),
    re_path(r'^data-source/(?P<pk>\d+)/history/$', views.data_source_history_list, name='data-source-history'),
    re_path(r'^data-source/(?P<pk>\d+)/history/(?P<log_pk>\d+)/download/$',
        views.data_source_history_download,
        name='data-source-history-download'),
    re_path(r'^data-source/(?P<pk>\d+)/history/(?P<log_pk>\d+)/restoration/$',
        views.data_source_history_restoration,
        name='data-source-history-restoration'),

    re_path(r'^data-source/(?P<pk>\d+)/transfer/$', views.data_source_initiate_ownership_transfer,
        name='data-source-initiate-transfer'),
    re_path(r'^data-source/transfer/(?P<datab64>[0-9A-Za-z_\-]+)/(?P<ts>[0-9A-Za-z_\-]+)/(?P<sig>[0-9A-Za-z_\-]+)/$',
        views.data_source_verified_transfer_ownership,
        name='data-source-verified-transfer'),

    path('virus/', views.VirusListView.as_view(), name='virus-list'),
    re_path(r'^virus/(?P<pk>\d+)/$', views.VirusDetailView.as_view(), name='virus-detail'),
    re_path(r'^virus/(?P<pk>\d+)/download/$', views.virus_download, name='virus-download'),

    path('host/', views.HostListView.as_view(), name='host-list'),
    re_path(r'^host/(?P<pk>\d+)/$', views.HostDetailView.as_view(), name='host-detail'),
    re_path(r'^host/(?P<pk>\d+)/download/$', views.host_download, name='host-download'),

    re_path(r'^response/ds-(?P<ds_pk>\d+)-virus-(?P<virus_pk>\d+)-host-(?P<host_pk>\d+)/update/$',
        views.response_update, name='response-update'),
    re_path(r'^response/virus-(?P<virus_pk>\d+)-host-(?P<host_pk>\d+)/$',
        views.response_detail, name='response-detail'),
    path('search/', views.search, name='search'),

    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),

    re_path(r'^host/(?P<pk>\d+)/$', views.HostDetailView.as_view(), name='host-detail'),

]

src/viralhostrange/viralhostrangedb/models.py
import colorsys
import re
import traceback

from basetheme_bootstrap import user_preferences
from colorfield.fields import ColorField
from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.mail import mail_admins
from django.core.validators import MaxLengthValidator
from django.db import models
# Create your models here.
from django.db.models import Exists, OuterRef, Q
from django.db.models.functions import Upper
from django.urls import reverse
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.utils.translation import gettext_lazy as _, gettext

from viralhostrangedb import business_process


class GlobalViralHostResponseValue(models.Model):
    class Meta:
        verbose_name = _("Global Viral-Host response values")
        verbose_name_plural = _("Global Viral-Host response values")

        index_together = [
            ["id", "name"],
            ["id", "value"],
            ["id", "name", "value"],
        ]

        permissions = (
            ("change_globalviralhostresponsevalue_color", "Can change Global Viral-Host response color"),
        )

    name = models.CharField(
        verbose_name=_("response__name__verbose_name"),
        help_text=_("response__name__help_text"),
        max_length=32,
        validators=[MaxLengthValidator(32)] if settings.DEBUG else [],
        unique=True,
    )
    description = models.TextField(
        verbose_name=_("response__description__verbose_name"),
        help_text=_("response__description__help_text"),
        blank=True,
        default="",
    )
    value = models.FloatField(
        verbose_name=_("response__value__verbose_name"),
        help_text=_("response__value__help_text"),
        default=-1000000,
    )
    color = ColorField(
        verbose_name=_("response__color__verbose_name"),
        help_text=_("response__color__help_text"),
    )

    def __str__(self):
        return "%s (value=%s)" % (self.name, '{0:g}'.format(self.value))

    def to_hsv(self):
        h, s, v = colorsys.rgb_to_hsv(
            int("0x" + self.color[1:3], 0) / 255,
            int("0x" + self.color[3:5], 0) / 255,
            int("0x" + self.color[5:7], 0) / 255,
        )
        return h * 360, s * 100, v * 50

    @classmethod
    def get_hsv_color_for(cls, value):
        lower = cls.objects_mappable().filter(value__lte=value).order_by("-value").first()
        upper = cls.objects_mappable().filter(value__gte=value).order_by("value").first()
        lower_hsv = lower.to_hsv()
        upper_hsv = upper.to_hsv()
        if lower.value == upper.value:
            percentage = 0
        else:
            percentage = (value - lower.value) / (upper.value - lower.value)

        hue = lower_hsv[0] * percentage + upper_hsv[0] * (1 - percentage)
        sat = lower_hsv[1] * percentage + upper_hsv[1] * (1 - percentage)
        lgt = lower_hsv[2] * percentage + upper_hsv[2] * (1 - percentage)
        return hue, sat, lgt

    @classmethod
    def get_rgb_color_for(cls, value):
        hue, sat, lgt = cls.get_hsv_color_for(value=value)
        r, g, b = colorsys.hsv_to_rgb(hue / 360, sat / 100, lgt / 50)
        return int(r * 255), int(g * 255), int(b * 255)

    @classmethod
    def get_html_color_for(cls, value):
        r, g, b = cls.get_rgb_color_for(value)
        return '#%02x%02x%02x' % (r, g, b)

    @staticmethod
    def get_not_mapped_yet_keyword():
        return 'NOT MAPPED YET'

    @staticmethod
    def get_not_mapped_yet():
        return GlobalViralHostResponseValue.objects.get(
            name=GlobalViralHostResponseValue.get_not_mapped_yet_keyword())

    @staticmethod
    def get_not_mapped_yet_pk():
        return GlobalViralHostResponseValue.objects.filter(
            name=GlobalViralHostResponseValue.get_not_mapped_yet_keyword()).values_list('pk', flat=True)[0]

    @classmethod
    def objects_mappable(cls):
        return cls.objects.filter(~Q(name=cls.get_not_mapped_yet_keyword()))


class DataSource(models.Model):
    class Meta:
        verbose_name = _("Data Source")
        verbose_name_plural = _("Data Sources")
        ordering = [Upper('name'), ]

    @classmethod
    def get_objects_annotated_with_pending(cls, qs=None):
        if qs is None:
            qs = DataSource.objects.all()
        pending = DataSource.objects.all().filter(
            responseindatasource__response=GlobalViralHostResponseValue.get_not_mapped_yet()
        ).filter(pk=OuterRef('pk'))
        return qs.annotate(
            mapping_done=~Exists(pending)
        )

    owner = models.ForeignKey(
        to=get_user_model(),
        on_delete=models.PROTECT,
    )
    provider_last_name = models.CharField(
        verbose_name=_("data_source__provider_last_name__verbose_name"),
        help_text=_("data_source__provider_last_name__help_text"),
        max_length=64,
        validators=[MaxLengthValidator(64)] if settings.DEBUG else [],
        blank=True,
        null=True,
    )
    provider_first_name = models.CharField(
        verbose_name=_("data_source__provider_first_name__verbose_name"),
        help_text=_("data_source__provider_first_name__help_text"),
        max_length=64,
        validators=[MaxLengthValidator(64)] if settings.DEBUG else [],
        blank=True,
        null=True,
    )
    public = models.BooleanField(
        verbose_name=_("public__verbose_name"),
        help_text=_("public__help_text"),
        default=False,
    )
    name = models.CharField(
        verbose_name=_("data_source__name__verbose_name"),
        help_text=_("data_source__name__help_text"),
        max_length=128,
        validators=[MaxLengthValidator(128)] if settings.DEBUG else []
    )
    description = models.TextField(
        verbose_name=_("data_source__description__verbose_name"),
        help_text=_("data_source__description__help_text"),
        blank=True,
        default="",
    )
    raw_name = models.TextField(
        verbose_name=_("raw_name__verbose_name"),
        help_text=_("raw_name__help_text"),
    )
    kind = models.CharField(
        verbose_name=_("kind__verbose_name"),
        help_text=_("kind__help_text"),
        max_length=4,
        choices=(
            ("FILE", _("From a file")),
            ("URL", _("From an URL")),
            # ("LIVE", _("Live input")),
        )
    )
    allowed_users = models.ManyToManyField(
        to=get_user_model(),
        verbose_name=_("allowed_users__verbose_name"),
        help_text=_("allowed_users__help_text"),
        related_name='datasource_granted_set',
        blank=True,
        through="GrantedUser",
    )
    experiment_date = models.DateField(
        verbose_name=_("experiment_date__verbose_name"),
        help_text=_("experiment_date__help_text"),
        blank=True,
        null=True,
    )
    creation_date = models.DateTimeField(
        verbose_name=_("creation_date__verbose_name"),
        help_text=_("creation_date__help_text"),
    )
    last_edition_date = models.DateTimeField(
        verbose_name=_("last_edition_date__verbose_name"),
        help_text=_("last_edition_date__help_text"),
    )
    publication_url = models.URLField(
        verbose_name=_("publication_url__verbose_name"),
        help_text=_("publication_url__help_text"),
        null=True,
        blank=True,
    )
    life_domain = models.CharField(
        choices=(
            ("archaea", _("Archaea")),
            ("bacteria", _("Bacteria")),
            ("eukaryote", _("Eukaryote")),
        ),
        verbose_name=_("life_domain.label"),
        help_text=_("life_domain.help_text"),
        null=False,
        blank=False,
        default="bacteria",
        max_length=32,
    )

    def __str__(self):
        return "%s (created on %s)" % (
            self.name,
            "???" if self.creation_date is None else self.creation_date.strftime('%Y-%m-%d %H:%M:%S %Z'),
        )

    def get_absolute_url(self):
        return reverse("viralhostrangedb:data-source-detail", args=[self.pk])

    def get_ordered_mapping(self, only_pk=False):
        return self.get_mapping(ordered=True)

    def get_mapping(self, only_pk=False, ordered=False):
        if not only_pk:
            used_responses = dict()
            for r in GlobalViralHostResponseValue.objects.filter(
                    pk__in=self.responseindatasource.values_list('response__pk').distinct()):
                used_responses[r.pk] = r
        q = self.responseindatasource.values_list('raw_response', 'response__pk')
        if ordered:
            q = q.order_by("raw_response")
        for raw_response, response_mapped in q.distinct():
            yield raw_response, response_mapped if only_pk else used_responses[response_mapped]

    @property
    def is_mapping_done(self):
        return not ViralHostResponseValueInDataSource.objects \
            .filter(data_source__pk=self.pk, response__name=GlobalViralHostResponseValue.get_not_mapped_yet_keyword()) \
            .exists()

    @property
    def is_mapping_absent(self):
        return not GlobalViralHostResponseValue.objects \
            .filter(responseindatasource__data_source__pk=self.pk) \
            .filter(~Q(name=GlobalViralHostResponseValue.get_not_mapped_yet_keyword())) \
            .exists()

    @property
    def has_provider(self):
        return self.provider_last_name is not None \
               and self.provider_first_name is not None \
               and len(self.provider_last_name) > 0 \
               and len(self.provider_first_name) > 0

    @classmethod
    def get_not_mapped_data_sources(cls, *, owner):
        return cls.objects.filter(pk__in=cls.get_not_mapped_data_sources_pk(owner=owner))

    @classmethod
    def get_not_mapped_data_sources_pk(cls, *, owner):
        if owner.pk is None:
            return []
        return cls._get_not_mapped_data_sources(owner=owner) \
            .values_list("responseindatasource__data_source__pk", flat=True).distinct()

    @classmethod

src/viralhostrange/viralhostrangedb/templates/viralhostrangedb/index.html
{% extends "viralhostrangedb/base.html" %}
{%load sstatic%}
{%load i18n%}

{% block whole_content_page_title %}{% endblock %}
{% block title %}{%trans "ViralHostRangeDB" %}{% endblock %}
{% block page_title %}{%trans "ViralHostRangeDB" %}{% endblock %}
{% block container-class %}container-fluid{% endblock %}

{% block extra_css %}
{{block.super}}
<link rel="stylesheet" href="{% sstatic '/css/index.css' %}"/>
{% endblock %}

{% block content%}
{% url 'viralhostrangedb:data-source-create' as contribute_url %}
{% url 'viralhostrangedb:browse' as browse_url %}
{% url 'viralhostrangedb:browse' as analysis_tool_url %}
{% url 'viralhostrangedb:virus-list' as virus_list %}
{% url 'viralhostrangedb:host-list' as host_list %}
{% url 'basetheme_bootstrap:about_page' as cite_url %}
<div class="col-12 col-lg-10 offset-lg-1 col-xl-8 offset-xl-2 mt-4">
    <div class="row homepage-upper">
        <h1 class="col-12 text-center">{%trans "ViralHostRangeDB_main_title" %}</h1>
        <div class="col-12">
            <div class="card mb-4">
                <div class="card-body text-justify">
                    {%blocktrans %}short_description_app{{contribute_url}}{{virus_list}}{{browse_url}}{{host_list}}{{cite_url}}{{analysis_tool_url}}{%endblocktrans%}
                </div>
                <a href="{%url 'basetheme_bootstrap:about_page'%}" class="card-footer text-right bg-primary">
                    {% trans "More info"%} <i class="fa fa-arrow-right"></i>
                </a>
            </div>
        </div>
        <div class="col-12 col-md-4">
            <a href="{{browse_url}}" role="button"
               class="big-button bg-primary">
                <div class="img-holder"><img src="{% sstatic '/img/browse.png' %}"></div>
                <h4 class="pt-4 pl-4 pr-4"><i class="fa fa-table"></i> {% trans "Browse"%}</h4>
                <div class="pb-4">{% trans "hosts responses to viruses"%}</div>
            </a>
        </div>
        <div class="col-12 col-md-4">
            <a href="{{contribute_url}}" role="button"
               class="big-button bg-primary">
                <div class="img-holder"><img src="{% sstatic '/img/contribute.png' %}"></div>
                <h4 class="pt-4 pl-4 pr-4">
                    <i class="fa fa-database"></i> <i class="fa fa-plus fa-in-superscript"></i>
                    {% trans "Contribute"%}</h4>
                <div class="pb-4">{% trans "with your data"%}</div>
            </a>
        </div>
        <div class="col-12 col-md-4">
            <a href="{% url 'viralhostrangedb:search' %}" role="button"
               class="big-button bg-primary">
                <div class="img-holder"><img src="{% sstatic '/img/search.png' %}"></div>
                <h4 class="pt-4 pl-4 pr-4"><i class="fa fa-search"></i> {% trans "Search"%}</h4>
                <div class="pb-4">{% trans "in viruses, hosts and data sources"%}</div>
            </a>
        </div>
    </div>
</div>

{% if live_settings.number_of_recent_data_source != "0" %}
<div class="col-12 col-lg-10 offset-lg-1 col-xl-8 offset-xl-2">
    <h1 class="text-center mt-4 pt-4">{% trans "title_subset_of_data_source"%}</h1>
    <div class="row">
        {% for ds in top_data_sources %}
        <div class="col-12 col-md-6 mt-4">
            <div class="card card-data-source">
                <div class="card-body">
                    <span class="ds-name">
                    {{ds.name}}
                    </span>
                    <span class="ds-from">
                        ({%trans "From"%} {{ds.owner.last_name|upper}} {{ds.owner.first_name|title}}, {{ds.last_edition_date|date  }})
                    </span>
                    <div class="ds-shadow">
                    </div>
                    <div class="ds-desc">
                    {{ds.description|slice:":255"}}
                    </div>
                </div>
                <div class="card-footer">
                    <a href="{%url 'viralhostrangedb:data-source-browse' pk=ds.pk %}" class="bg-primary">
                        <i class="fa fa-table"></i> {%trans "Browse" %}
                    </a>
                    <a href="{%url 'viralhostrangedb:data-source-detail' pk=ds.pk %}" class="bg-primary">
                        <i class="fa fa-database"></i>
                        {%trans "Open" %}
                    </a>
                </div>
            </div>
        </div>
        {%endfor%}
    </div>
</div>
{%endif%}
<div class="col-12 col-lg-10 offset-lg-1 col-xl-8 offset-xl-2">
    <h1 class="text-center mt-4 pt-4">{% trans "access_to_virus_host_and_data_source"%}</h1>
    <div class="row homepage-lower">
        <div class="col-12 col-md-4">
            <a href="{% url 'viralhostrangedb:data-source-list' %}" role="button"
               class="homepage-lower-button bg-primary">
                <h4 class="pt-4 pl-4 pr-4">
                    <i class="fa fa-database"></i> {% trans "Data sources"%}</h4>
                <div class="pb-4">{% trans "Open the full list"%}</div>
            </a>
        </div>
        <div class="col-12 col-md-4">
            <a href="{{virus_list}}" role="button"
               class="homepage-lower-button bg-primary">
                <h4 class="pt-4 pl-4 pr-4">
                    <span class="btf-virus"></span> {% trans "Viruses"%}</h4>
                <div class="pb-4">{% trans "Open the full list"%}</div>
            </a>
        </div>
        <div class="col-12 col-md-4">
            <a href="{{host_list}}" role="button"
               class="homepage-lower-button bg-primary">
                <h4 class="pt-4 pl-4 pr-4">
                    <span class="btf-host"></span> {% trans "Hosts"%}</h4>
                <div class="pb-4">{% trans "Open the full list"%}</div>
            </a>
        </div>
        {%if live_settings.enable_meta_analysis == "True" %}
        <div class="col-12 col-md-4 offset-md-2">
            <a href="{% url 'viralhostrangedb:download_responses' %}?user_pref=False&only_host_ncbi_id=true&only_virus_ncbi_id=true&allow_overflow=on" role="button"
               class="homepage-lower-button bg-primary">
                <h4 class="pt-4 pl-4 pr-4">
                    <i class="fa fa-download"></i> {% trans "Meta analysis"%}</h4>
                <div class="pb-4 pl-1 pr-1">{% trans "Download all responses on NCBI identified viruses and hosts"%}</div>
            </a>
        </div>
        <div class="col-12 col-md-4">
            <a href="{% url 'viralhostrangedb:browse'             %}?user_pref=False&only_host_ncbi_id=true&only_virus_ncbi_id=true&allow_overflow=on" role="button"
               class="homepage-lower-button bg-primary">
                <h4 class="pt-4 pl-4 pr-4">
                    <i class="fa fa-table"></i> {% trans "Meta analysis"%}</h4>
                <div class="pb-4 pl-1 pr-1">{% trans "Explore all responses on NCBI identified viruses and hosts"%}</div>
            </a>
        </div>
        {%endif%}
    </div>
</div>
{% endblock content%}

src/viralhostrange/viralhostrangedb/templates/viralhostrangedb/login_menu.html
{% extends "basetheme_bootstrap/login_menu.html" %}
{% block login_menu_staff_dropdown_items %}
{{block.super}}
<a  class="dropdown-item" href="https://gitlab.pasteur.fr/hub/viralhostrangedb" target="_blank"><i class="fa fa-bug"></i> Issue tracking</a>
{% endblock %}

src/viralhostrange/viralhostrangedb/templates/viralhostrangedb/nav_bar.html
{% load  basetheme_bootstrap %}
{% load i18n %}
{% load viralhostrange_tags %}
<li class="nav-item d-sm-none d-md-none d-lg-none d-xl-none"><a class="nav-link" href="{% url 'viralhostrangedb:home'%}"> {%trans "Home"%}</a></li>
<li class="nav-item {{ request|is_active_or_desc:'viralhostrangedb:browse'}}"><a class="nav-link" href="{% url 'viralhostrangedb:browse'%}"><i class="fa fa-table"></i> {%trans "Browse"%}</a></li>
<li class="nav-item {{ request|is_active_or_desc:'viralhostrangedb:data-source-create'}}"><a class="nav-link" href="{% url 'viralhostrangedb:data-source-create'%}">
   <i class="fa fa-database"></i> <i class="fa fa-plus fa-in-superscript"></i> {%trans "Contribute"%}
</a></li>
<li class="nav-item hidden-in-header"><a class="nav-link" href="{% url 'viralhostrangedb:data-source-list'%}"><i class="fa fa-database"></i> {%trans "Data sources"%}</a></li>
<li class="nav-item hidden-in-header"><a class="nav-link" href="{% url 'viralhostrangedb:virus-list'%}">
    <span class="btf-virus"></span> {%trans "Viruses"%}</a></li>
<li class="nav-item hidden-in-header"><a class="nav-link" href="{% url 'viralhostrangedb:host-list'%}"><span class="btf-host"></span> {%trans "Hosts"%}</a></li>
<li class="nav-item"><a class="nav-link" href="{% url 'viralhostrangedb:search'%}"><i class="fa fa-search"></i> {%trans "Search"%}</a></li>
<li class="nav-item hidden-in-header"><a class="nav-link" href="http://hub.pages.pasteur.fr/viralhostrangedb/"><i class="fa fa-book"></i> {%trans "Documentation"%}</a></li>
<li class="nav-item {{ request|is_active_or_desc:'basetheme_bootstrap:about_page'}}"><a class="nav-link" href="{% url 'basetheme_bootstrap:about_page'%}"><i class="fa fa-question-circle"></i> {%trans "About"%}</a></li>
<form class="form-inline d-sm-none d-md-none d-lg-none d-xl-none" action="{% url 'viralhostrangedb:search' %}"  method="post">{% csrf_token %}
    <input class="form-control" name="search" type="text" value="{{search_bar_value}}" placeholder="{%trans 'Type your search here'%}" aria-label="Search">
</form>

src/viralhostrange/viralhostrangedb/templates/viralhostrangedb/upper_nav_bar.html
{% extends "basetheme_bootstrap/upper_nav_bar.example.html" %}